---

mgmt_host: "{{ groups['one-mgmt'][0] }}"

packages_to_install:
    - gcc
    - rubygem-rake
    - libxml2-devel
    - libxslt-devel
    - patch
    - gcc-c++
    - sqlite-devel
    - curl-devel
    - mysql-devel
    - openssl-devel
    - ruby-devel
    - make

gems_to_install:

    - { name: 'sqlite3', version: '1.3.13' }
    - { name: 'nokogiri', version: '1.6.8.1' }
    - { name: 'net-ldap', version: '0.16.1' }
    - { name: 'zendesk_api', version: '1.16.0' }
    - { name: 'rack', version: '1.6.10' }
    - { name: 'rack-protection', version: '1.5.5' }
    - { name: 'sequel', version: '5.7.1' }
    - { name: 'sinatra', version: '1.4.8' }
    - { name: 'thin', version: '1.7.2' }
    - { name: 'memcache-client', version: '1.8.5' }
    - { name: 'uuidtools', version: '2.1.5' }
    - { name: 'curb', version: '0.9.4' }
    - { name: 'configparser', version: '0.1.7' }
    - { name: 'azure', version: '0.7.10' }
    - { name: 'azure-core', version: '0.1.14' }
    - { name: 'parse-cron', version: '0.1.4' }
    - { name: 'amazon-ec2', version: '0.9.17' }
    - { name: 'aws-sdk', version: '2.11.39' }
    - { name: 'aws-sdk-core', version: '2.11.39' }
    - { name: 'aws-sdk-resources', version: '2.11.39' }
    - { name: 'aws-sigv4', version: '1.0.2' }
    - { name: 'ox', version: '2.9.2' }
    - { name: 'mysql2', version: '0.5.1' }
    - { name: 'builder', version: '3.2.3' }
    - { name: 'bundler', version: '1.17.1' }


gems_to_install_full:
    - { name: 'addressable', version: '2.5.2' }
    - { name: 'amazon-ec2', version: '0.9.17' }
    - { name: 'aws-sdk', version: '2.11.39' }
    - { name: 'aws-sdk-core', version: '2.11.39' }
    - { name: 'aws-sdk-resources', version: '2.11.39' }
    - { name: 'aws-sigv4', version: '1.0.2' }
    - { name: 'azure', version: '0.7.10' }
    - { name: 'azure-core', version: '0.1.14' }
    - { name: 'bigdecimal', version: '1.2.0' }
    - { name: 'builder', version: '3.2.3' }
    - { name: 'bundler', version: '1.17.1' }
    - { name: 'configparser', version: '0.1.7' }
    - { name: 'curb', version: '0.9.4' }
    - { name: 'daemons', version: '1.2.6' }
    - { name: 'eventmachine', version: '1.2.5' }
    - { name: 'faraday', version: '0.15.0' }
    - { name: 'faraday_middleware', version: '0.12.2' }
    - { name: 'hashie', version: '3.5.7' }
    - { name: 'inflection', version: '1.0.0' }
    - { name: 'io-console', version: '0.4.2' }
    - { name: 'jmespath', version: '1.4.0' }
    - { name: 'json', version: '1.7.7' }
    - { name: 'memcache-client', version: '1.8.5' }
    - { name: 'mime-types', version: '3.1' }
    - { name: 'mime-types-data', version: '3.2016.0521' }
    - { name: 'mini_portile2', version: '2.1.0' }
    - { name: 'multipart-post', version: '2.0.0' }
    - { name: 'mysql2', version: '0.5.1' }
    - { name: 'net-ldap', version: '0.16.1' }
    - { name: 'nokogiri', version: '1.6.8.1' }
    - { name: 'ox', version: '2.9.2' }
    - { name: 'parse-cron', version: '0.1.4' }
    - { name: 'polyglot', version: '0.3.5' }
    - { name: 'psych', version: '2.0.0' }
    - { name: 'public_suffix', version: '2.0.5' }
    - { name: 'rack', version: '1.6.10' }
    - { name: 'rack-protection', version: '1.5.5' }
    - { name: 'rake', version: '0.9.6' }
    - { name: 'rdoc', version: '4.0.0' }
    - { name: 'scrub_rb', version: '1.0.1' }
    - { name: 'sequel', version: '5.7.1' }
    - { name: 'sinatra', version: '1.4.8' }
    - { name: 'sqlite3', version: '1.3.13' }
    - { name: 'systemu', version: '2.6.5' }
    - { name: 'thin', version: '1.7.2' }
    - { name: 'thor', version: '0.20.0' }
    - { name: 'tilt', version: '2.0.8' }
    - { name: 'treetop', version: '1.6.10' }
    - { name: 'trollop', version: '2.1.2' }
    - { name: 'uuidtools', version: '2.1.5' }
    - { name: 'xml-simple', version: '1.1.5' }


