---

- name: install packages kvm-node
  action: yum name={{ item }}
  with_items: 
    - qemu-kvm 
    - libvirt
    - libvirt-python
    - libguestfs-tools
    - virt-install
    - centos-release-qemu-ev
    #- qemu-kvm-ev
    - opennebula-node-kvm
    
- name: restart libvirtd
  service: name=libvirtd state=restarted

- name: ssh config between hosts (from mgmt_host)
  shell: |
    su oneadmin
    ssh-keyscan {{ mgmt_host }} {{ kvm_host }} >> /var/lib/one/.ssh/known_hosts
    scp -rp /var/lib/one/.ssh {{ kvm_host }}:/var/lib/one/
  delegate_to: "{{ mgmt_host }}"



##########################
- name: configure udev
  action: copy src=80-kvm.rules dest=/etc/udev/rules.d/80-kvm.rules owner=root group=root mode=644

- name: configure libvirt
  action: template src=libvirtd.conf.j2 dest=/etc/libvirt/libvirtd.conf 
  notify: restart libvirtd

- name: fetch oneadmin ssh public key
  action: fetch dest=/tmp src=/var/lib/one/.ssh/{{ item }}
  with_items:
    - id_dsa.pub
    - id_rsa.pub
    - config
    - id_dsa
    - id_rsa
  delegate_to: "{{ mgmt_host }}"

- name: configure ssh authorized keys
  action: authorized_key user=oneadmin key="{{ lookup('file', '/tmp/' + mgmt_host + '/var/lib/one/.ssh/' + item  ) }}"
  with_items:
    - id_dsa.pub
    - id_rsa.pub

- name: copy ssh keys and files to host
  action: copy src=/tmp/{{ mgmt_host }}/var/lib/one/.ssh/{{ item }} dest=/var/lib/one/.ssh owner=oneadmin group=oneadmin
  with_items:
    - id_dsa.pub
    - id_dsa
    - id_rsa.pub
    - id_rsa
    - config

- name: set SELinux label on authorized_keys
  action: file path=/var/lib/one/.ssh/authorized_keys setype=ssh_home_t

